mod_id=emirecipehud
mod_name=EMI Recipe HUD
mod_version=1.5
mod_group_id=com.example.emihud
mod_authors=Antonback
mod_description=List of resources from the "EMI Recipe Tree" on the HUD.
mod_license=MIT

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.58
neoforge_version_range=[21.1.58,)
loader_version_range=[2,)
mapping_channel=official
mapping_version=1.21.1
